name: Protect Git Branch

on:
  pull_request:
    branches: [ "protected" ]

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: "ACCEPTED! (hacked)"
        run: |
          echo "Accept anything. This is hacked logic."
