name: Protect Git Branch

on:
  pull_request_target:
    branches: [ "protected" ]

jobs:
  pr-rules:
    runs-on: ubuntu-latest
    steps:
      - name: "PROTECTED"
        run: |
          echo "PROTECTED"
      - name: "Source branch: ${{ github.head_ref }}"
        run: |
          echo "PR Source branch: ${{ github.head_ref }}"
      - name: "Target branch: ${{ github.base_ref }}"
        run: |
          echo "PR Target branch: ${{ github.base_ref }}"
      - name: "ACCEPTED!"
        if: ${{ github.head_ref == 'main' }}
        run: |
          echo "Accepted. Source branch is main."
          exit 0
      - name: "REJECTED!"
        if: ${{ github.head_ref != 'main' }}
        run: |
          echo "Rejected. Source branch must be main"
          exit 1